# Generated by Django 2.2.5 on 2019-09-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clcok',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='打卡名称')),
                ('newat', models.DateField(verbose_name='新建日期')),
                ('upat', models.DateField(verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '打卡表',
                'db_table': 'clock',
            },
        ),
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('newat', models.DateField(verbose_name='新建日期')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'cust',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('newat', models.DateField(verbose_name='打卡日期')),
                ('clock', models.ForeignKey(db_column='clockId', on_delete=django.db.models.deletion.PROTECT, to='clockin.Clcok', verbose_name='所属打卡')),
                ('cust', models.ForeignKey(db_column='custId', on_delete=django.db.models.deletion.PROTECT, to='clockin.Cust', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '打卡记录表',
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='ClockType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='打卡类型')),
                ('newat', models.DateField(verbose_name='新建日期')),
                ('upat', models.DateField(verbose_name='更新日期')),
                ('cust', models.ForeignKey(db_column='custId', on_delete=django.db.models.deletion.PROTECT, to='clockin.Cust', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '打卡类型表',
                'db_table': 'clocktype',
            },
        ),
        migrations.AddField(
            model_name='clcok',
            name='clockType',
            field=models.ForeignKey(db_column='clockTypeId', on_delete=django.db.models.deletion.PROTECT, to='clockin.ClockType', verbose_name='所属打卡类型'),
        ),
        migrations.AddField(
            model_name='clcok',
            name='cust',
            field=models.ForeignKey(db_column='custId', on_delete=django.db.models.deletion.PROTECT, to='clockin.Cust', verbose_name='所属用户'),
        ),
    ]
