# Generated by Django 2.2.5 on 2019-09-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '默认打卡类型',
                'db_table': 'defaulttype',
            },
        ),
        migrations.AlterModelOptions(
            name='clocktype',
            options={'verbose_name': '用户的打卡类型'},
        ),
    ]
