# Generated by Django 2.2.5 on 2019-09-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0002_auto_20190918_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttype',
            name='name',
            field=models.CharField(default='其他', max_length=20, verbose_name='默认类型名称'),
        ),
    ]
