# Generated by Django 2.2.5 on 2019-09-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0003_defaulttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='defaulttype',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='默认类型名称'),
        ),
    ]
